server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:ticketsdb
    driverClassName: org.h2.Driver
    username: somebody
    password: needs_money
  jpa:
    open-in-view: false
  cache:
    jcache.config: classpath:ehcache.xml

logging:
  level:
    org.springframework:
      web:
        filter.CommonsRequestLoggingFilter: DEBUG
